### ISSUE TITLE
Issue with mapping from MonoDB proxy object to dto

### ISSUE THREAD

**Issue by gabplch** [rekalogika/mapper#106]
While trying to map from a proxy receiving an error that can't instantiate an object from a possible proxy
![image](https://github.com/user-attachments/assets/0c76cc51-78f4-4c2f-8800-819ef52cf574)

**Comment by priyadi** [comment]
should be fixed in latest tag. let me know if the problem still persists.

**Comment by gabplch** [comment]
It looks like it was fixed, Thanks!
