### ISSUE TITLE
Setting union types as argument for ObjectMapper throws an error

### ISSUE THREAD

**Issue by gabplch** [rekalogika/mapper#110]
I'm trying to map with an object mapper but receiving an error.

<img width="478" alt="image" src="https://github.com/user-attachments/assets/f9dbf6c1-7e99-4197-98e3-59300ca0c741">

Example:
```php
...
#[AsObjectMapper]
public function mapFooBar (
    Foo|Bar $obj
): Baz {
    ...
}

**Comment by gabplch** [comment]
Guess, that same will be with AsPropertyMapper

**Comment by priyadi** [comment]
Union types are not yet supported, but in the meantime, you should be able to rewrite that like this:

```php
#[AsObjectMapper]
public function mapFoo (
    Foo $obj
): Baz {
    return $this->mapFooBar(Foo|Bar $obj);
}

#[AsObjectMapper]
public function mapBar (
    Bar $obj
): Baz {
    return $this->mapFooBar(Foo|Bar $obj);
}

private function mapFooBar (
    Foo|Bar $obj
): Baz {
    ...
}
```

This should be straightforward to implement, though. I'll see what I can do in a few days.

**Comment by priyadi** [comment]
implemented in https://github.com/rekalogika/mapper/pull/114 and https://github.com/rekalogika/mapper/pull/115
