### ISSUE TITLE
"Allow dynamic properties" tries to map `null` onto target properties, missing in source

### ISSUE THREAD

**Issue by rsavuliak-macpaw** [rekalogika/mapper#112]
The issue is, when using dynamic properties functionality - is that it behaves, like my source class should have some magic methods to resolve ALL properties from target. However it is not - it's just a simple class, with a defined set of properties which are a subset of target class properties. I do not expect to set all target properties, however logic forces me to do so cause it treates the value of each missing property in source as `null`, like it exists there.

```php
class Source extends \stdClass
{
}

class Target
{
    public int $a;
    
    public \DateTime $b;
}
```

Execution
```php
$source = new Source;
$source->a = 10;

$this->map($source, Target::class);

// Cannot find a matching transformer for mapping the source types "null" to the target types "DateTime". Mapping path: "b".
```

When object with a defined properties is used and it also contains subset of properties - mapper does not try to set other target properties. So I expect the same behaviour with object of dynamic properties.

I think there should be a way to separate this behaviour by checking for any magic methods for non-existing properties. Otherwise, it's not quite correct to merge source dynamic properties  with target and just replacing missing ones with `null`, cause it won't work, if target property does not allow `null`.

**Comment by priyadi** [comment]
I'm not sure if I understand everything you say. My understanding is that from your example, you expect mapper to ignore $a & $b, and leave those properties unset? Or, are there other cases you have in mind?

**Comment by priyadi** [comment]
it should be fixed now. let me know if there are other cases not resolved by the change.

**Comment by rsavuliak-macpaw** [comment]
I will test it more in real code examples, but according to your changes, looks like you've understand it correctly ) Srry for bad explanation.

The idea was, that mapper tried to map property from Dynamic source, even if there was no such property there. So in such case it used `null` as fallback. And unfortunately it didn't work on properties, which do not support `null` and died with exception.
