### ISSUE TITLE
[Bug] Mapping object to `stdClass` loses explicetly set nullable property since `1.9.0`

### ISSUE THREAD

**Issue by ToshY** [rekalogika/mapper#198]
**Problem**

Since `1.9.0` (using `1.9.2` currently) the mapper stopped mapping nullable property values to `stdClass`.

**Reproduction**

```php
class Book
{
    public function __construct(
        public int $id,
        public ?int $completed,
    ) {
    }
}
```

Then calling the mapper:

```php
$result = $this->mapper->map(
    new Book(1, null),
    new \stdClass(),
);
```

In `=<1.8.0`:

```php
^ {#546
  +"id": 1
  +"completed": null
}
```

In `>=1.9.0`:

```php
^ {#547
  +"id": 1
}
```

**Comment by priyadi** [comment]
Should be fixed by https://github.com/rekalogika/mapper/pull/199 and v1.9.3. Thank you for your report.

**Comment by ToshY** [comment]
@priyadi  Thanks for the fast fix as always 💯
