### ISSUE TITLE
[Bug] Segmentation fault in non symfony projects

### ISSUE THREAD

**Issue by misterxan** [rekalogika/mapper#251]
### Bug Report: Segmentation Fault in MapperFactory

**Summary:**
A segmentation fault occurs when attempting to use `MapperFactory` outside the Symfony context. This issue is triggered by the script entering an infinite loop, resulting in a segmentation fault.

**Steps to Reproduce:**
1. Use `MapperFactory` in a non-Symfony environment.
2. Observe that the script enters an infinite loop and eventually results in a segmentation fault.

**Details of the Infinite Loop:**
The issue appears in the following code snippets:

**1. MapperFactory.php:701**
```php
protected function getTransformersLocator(): ContainerInterface
{
    /** @psalm-suppress InvalidArgument */
    return new ServiceLocator(iterator_to_array($this->getTransformersIterator()));
}
```

**2. MapperFactory.php:645**
```php
yield 'ObjectMapperTransformer' => $this->getObjectMapperTransformer();
```

**3. MapperFactory.php:446**
```php
$this->objectMapperTransformer = new ObjectMapperTransformer(
    $this->getSubMapperFactory(),
    $this->getTransformersLocator(), //HERE
    $this->getObjectMapperTableFactory(),
    $this->getObjectMapperResolver(),
);
```

**Problem Analysis:**
- The call to `$this->getTransformersLocator()` in `MapperFactory.php:446` creates a recursive call that leads back to `MapperFactory.php:701`, resulting in an infinite loop.
- This issue occurs due to the way dependencies are being resolved within `getTransformersLocator()` and `getObjectMapperTransformer()`.

**Expected Behavior:**
`MapperFactory` should properly initialize without entering an infinite loop when used outside the Symfony context.

**Actual Behavior:**
The script enters an infinite loop, eventually causing a segmentation fault.

**Environment:**
- PHP Version: 8.2
- Symfony Version: N/A (outside of Symfony context)
- Operating System: MacOS

**Possible Solutions:**
- Investigate the dependency resolution within `getTransformersLocator()` and `getObjectMapperTransformer()`.
- Refactor the logic to prevent recursive calls that lead to infinite loops.

**Attachments/References:**
- Code snippets are provided above for detailed inspection.

**Comment by misterxan** [comment]
@priyadi fyi

**Comment by priyadi** [comment]
It is fixed in the related PR. However, `MapperFactory` is currently only lightly tested. Feel free to open more issues if you encounter more problems.

**Comment by misterxan** [comment]
Thanks a lot!
