### ISSUE TITLE
Cache key contains reserved characters `{}()/\@:`

### ISSUE THREAD

**Issue by ToshY** [rekalogika/mapper#3]
**Problem**

Trying to map one object to another object, `$this->mapper->map($dto, $entity);` fails due to invalid cache key name:

```text
Cache key "App\DTO\BookDto:App\Entity\Book" contains reserved characters "{}()/\@:".
```

**Cause**

Invalid cache key name is created here:

https://github.com/rekalogika/mapper/blob/28abf78ce8ac177faa9fd60f599c47839a79bf09/src/Transformer/ObjectToObjectMetadata/Implementation/CachingObjectToObjectMetadataFactory.php#L73

**Reproduction**

* Symfony setup (6.4+) with Redis cache adapter
  * It should not matter which type of cache adapter you'd use to reproduce, as all adapters extend from the Symfony `AbstractAdapter`, which use the `AbstractAdapterTrait` to validate the key name.

**Version**

* `rekalogika/mapper`: `v0.8.0`
* `symfony/cache`: `v7.0.3`

**Comment by ToshY** [comment]
@priyadi Thanks for the quick fix. Any chance you can tag a new release?

**Comment by priyadi** [comment]
@ToshY Tagged. Enjoy!
