### ISSUE TITLE
Mapper casts nulllable property to string when not using constructor property promotion in target class

### ISSUE THREAD

**Issue by ToshY** [rekalogika/mapper#4]
**Problem**

I've noticed that nullable properties get cast to empty string (`""`) instead of being kept as `null` value when not using constructor property promotion in the target class.

**Reproduction**

`src/Dto/BookDto.php`
```php
namespace App\Dto;

class BookDto
{
    public function __construct(
        public string|null $title = null,
    ) {
    }
}
```

`src/Entity/Book.php`
```php
namespace App\Entity;

class Book
{
    private string|null $title = null;

    public function __construct(
        private int $id,
    ) {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }
}
```

Run mapper

```php
$book = new \App\Entity\Book(1);
$this->mapper->map(new \App\Dto\BookDto(null), $book);
```

Result

```txt
App\Entity\Book {#2485 ▼
  -id: 1
  -notes: ""
}

**Comment by priyadi** [comment]
Good catch. Should be fixed in https://github.com/rekalogika/mapper/commit/9f905f6f7f72fdab17b8ade87c99220b1d817643#diff-f83e47d2f91e3e2387942cb949109e8c35e2de12bc52d1f5b2980a4cedc81ab0 . Thank you.
