### ISSUE TITLE
[Question] - Nested objects

### ISSUE THREAD

**Issue by pedrem** [rekalogika/mapper#52]
Question

Is it possible to map a DTO with nested objects to an entity and also fetch those relations?
This problems occures from DTO -> entity, from entity -> DTO the mapping populates everything as expected.

Here's an example, the simple types are fetched correctly, but not the relations, either collection (colours) or simple entity (featuredColour). Am I missing some sort of configuration?

Example:

``` 
class ProductDto
{
    public ?int $productId = null;

    public ?ColourDto $$featuredColour = null;

    #[Assert\NotNull]
    #[Assert\Type('boolean')]
    public ?bool $enabled = null;

    #[Assert\NotNull]
    #[Assert\Type('boolean')]
    public ?bool $featured = null;

    /** @var ?array<int,ColourDto> */
    public ?array $colours = null;
}
```

I would also like to know if it's possible to map array to array, is it possible in this current version? 
So let's imagine an API where it returns a collection of objects, I would image it something like below
```
return $this->mapper->mapArray($entityCollection, Dto:class)
```

Thank you!

**Comment by priyadi** [comment]
Your provided example should work, as long as the source `Product` has `$featuredColour` and `$colours`. Can you provide a minimal working reproducer?

Regarding your second question, it seems a popular request and I already have the following in my local repository:

```php
namespace Rekalogika\Mapper;

use Rekalogika\Mapper\Context\Context;

interface CollectionMapperInterface
{
    /**
     * @template T of object
     * @param iterable<mixed> $source
     * @param class-string<T> $target
     * @return iterable<T>
     */
    public function mapCollection(iterable $source, string $target, ?Context $context = null): iterable;
}
```

I'll try finishing the work this weekend.

**Comment by priyadi** [comment]
I already released v1.2.0 that provides `IterableMapperInterface`

**Comment by priyadi** [comment]
Alright, it looks like you are under the impression that the mapper should map the DTO to the corresponding existing entity from the persistence layer. However, the mapper is only a mapper, it doesn't know Doctrine or how to retrieve the entity from the database.

If you want to do that, you need to provide the mapper with the logic. One way to do it is using an object mapper:

```php
namespace App\Mapper;

use App\Dto\ColourDto;
use App\Entity\Colour;
use App\Repository\ColourRepository;
use Rekalogika\Mapper\Attribute\AsObjectMapper;

class ColourDtoToColourMapper
{
    public function __construct(
        private ColourRepository $colourRepository
    ) {
    }

    #[AsObjectMapper]
    public function mapColourDtoToColour(ColourDto $colourDto): Colour
    {
        $colour = $this->colourRepository->find($colourDto->id);

        if (!$colour) {
            throw new \Exception('Colour not found'); // maybe create a new colour instead if not found?
        }
        
        return $colour;
    }
}
```

Now every time you map a `ColourDto` to `Colour`, the mapper will look if there is an existing `Colour` in the database, and use it as the result.

Custom object mapper documentation: https://rekalogika.dev/mapper/object-mapper

My fork of your reproducer that contains the code above: https://github.com/priyadi/rekalogika-nested/tree/tinker

**Comment by pedrem** [comment]
That makes sense! I've added the to my project and it fetches the entities nicely!

I'm having a different issue now, I'm trying to create a PUT request for that same resource, it picks and adds the colours correctly, but doesn't remove them. 

I've updated the reproducer with the PUT.  We also noticed that on you have a `AdderTest`but no remover.

Thank you so much for the quick responses, it's been a huge help!

**Comment by priyadi** [comment]
The mapper does not currently support removal from the target object. But let me see your code first if I can offer other approaches to the problem. However, I don't see the new code in your repository. Make sure you have pushed the code to the repository.

**Comment by rsavuliak-macpaw** [comment]
I have a question that looks very similar to the title of this one, about nested objects: when I use target as class-string, everything works as a charm, all types of objects created correctly. However, when I use existing object and trying to map source onto it - it ignores all the properties changes on lower levels. Is is expected behaviour and I have to write custom mappers for each nested object? Or maybe there is some specific config I am missing?

**Comment by pedrem** [comment]
> The mapper does not currently support removal from the target object. But let me see your code first if I can offer other approaches to the problem. However, I don't see the new code in your repository. Make sure you have pushed the code to the repository.

Sorry, forgot to hit push! 
Anyway it's really just a simple PUT endpoint where we expect that the when colours get added/removed from the colours collection they get removed on the target.

**Comment by priyadi** [comment]
> Sorry, forgot to hit push! Anyway it's really just a simple PUT endpoint where we expect that when colours get added/removed from the colours collection they get removed on the target.
> 
> I'm not really sure how the library is handling and the depths of it, but would using something like https://symfony.com/doc/current/components/property_access.html#writing-to-array-properties help get this feature?

Yeah, the remove feature is beginning to look like an unfortunate omission. But we need to consider many things. These are what I can come up with:

How do we do it? Iterate the target collection, and remove the ones not included in the source? Or call clear() in the beginning, and only use the adder? With the latter, it only works with a Doctrine Collection on the target.

What if the target is an extra-lazy collection with 1000000000 records? Removal would be impossible, but adding is still realistic. Therefore, the feature needs to be opt-in, like with Symfony Form.

How the user can opt-in for the feature? Probably attributes.

How other mappers do it? Jolicode and Automapper-plus don't appear to support it directly. API Platform seems to support it using Property Access like you mentioned.

We used to use Property Access, but now we are using low-level code for performance.

**Comment by priyadi** [comment]
@pedrem I think it is done. Please verify if it is working in my branch: https://github.com/priyadi/rekalogika-nested/tree/tinker

**Comment by pedrem** [comment]
> @pedrem I think it is done. Please verify if it is working in my branch: https://github.com/priyadi/rekalogika-nested/tree/tinker

It's working perfectly now! I salute you for jumping into this issue so quickly. Thank you!

**Comment by priyadi** [comment]
Documentation is done: https://rekalogika.dev/mapper/collection#deleting-items-on-the-target-side-not-present-in-source
